#ifndef _GEOMETRY_H_
#define _GEOMETRY_H_

#define CUBE_N_VERTS 24
#define DPYRAMID_N_VERTS 24

extern float CUBE_VERTS[3*CUBE_N_VERTS];
extern float CUBE_NORMALS[3*CUBE_N_VERTS];

extern float DPYRAMID_VERTS[3*DPYRAMID_N_VERTS];
extern float DPYRAMID_NORMALS[3*DPYRAMID_N_VERTS];

#endif
